# File .github/workflows/notify_team.yml
name: Notify Team

on:
  workflow_call:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Notify team
        run: echo "Changes detected. Notify team via email."

#--------------------------------------------------------------------------------------------------

# File .github/workflows/notify_backend.yml
name: Notify Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  call-notify:
    uses: ./.github/workflows/notify.yml


#--------------------------------------------------------------------------------------------------

# File .github/workflows/notify_frontend.yml
name: Notify Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  call-notify:
    uses: ./.github/workflows/notify.yml
