name: Deploy to Environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    outputs:
      result:
        description: "Deployment result"
        value: ${{ jobs.deploy.outputs.status }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      status: ${{ steps.set-status.outputs.value }}
    steps:
      - name: Deploy to ${{ inputs.environment }}
        run: |
          echo "🚀 Deploying to ${{ inputs.environment }} environment..."
          
      - name: Set output status
        id: set-status
        run: echo "value=success" >> $GITHUB_OUTPUT
