name: Deploy to Production on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy-if-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.check_labels.outputs.environments }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PR Labels
        id: check_labels
        uses: ./.github/actions/check-labels-action
        with:
          pr_number: ${{ github.event.pull_request.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: deploy-if-merged
    if: needs.deploy-if-merged.outputs.environments != '["none"]'
    strategy:
      matrix:
        environment: ${{ fromJson(needs.deploy-if-merged.outputs.environments) }}
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: ${{ matrix.environment }}